'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Consulta
    Public Property idConsulta As Integer
    Public Property idPaciente As Nullable(Of Integer)
    Public Property idMedico As Nullable(Of Integer)
    Public Property idEnfermedad As Nullable(Of Integer)
    Public Property descripcion As String

    Public Overridable Property Enfermedad As Enfermedad
    Public Overridable Property Medico As Medico
    Public Overridable Property Paciente As Paciente
    Public Overridable Property Recetas As ICollection(Of Receta) = New HashSet(Of Receta)

End Class
