'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Enfermedad
    Public Property idEnfermedad As Integer
    Public Property nombre As String
    Public Property Descripcion As String

    Public Overridable Property Consultas As ICollection(Of Consulta) = New HashSet(Of Consulta)

End Class
