'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class EspecialidadMedico
    Public Property idEspecialidadMedico As Integer
    Public Property idMedico As Nullable(Of Integer)
    Public Property idEspecialidad As Nullable(Of Integer)

    Public Overridable Property Especialidad As Especialidad
    Public Overridable Property Medico As Medico

End Class
