'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Medicamento
    Public Property idMedicamento As Integer
    Public Property nombre As String
    Public Property cantidad As Integer
    Public Property descripcion As String
    Public Property idProveedor As Nullable(Of Integer)

    Public Overridable Property Proveedor As Proveedor
    Public Overridable Property Recetas As ICollection(Of Receta) = New HashSet(Of Receta)

End Class
