'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Medico
    Public Property idMedico As Integer
    Public Property nombre As String
    Public Property apellido As String
    Public Property nacimiento As Date
    Public Property direccion As String
    Public Property genero As String
    Public Property edad As Integer

    Public Overridable Property Consultas As ICollection(Of Consulta) = New HashSet(Of Consulta)
    Public Overridable Property EspecialidadMedicoes As ICollection(Of EspecialidadMedico) = New HashSet(Of EspecialidadMedico)
    Public Overridable Property Operacions As ICollection(Of Operacion) = New HashSet(Of Operacion)

End Class
