'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Proveedor
    Public Property idProveedor As Integer
    Public Property nombre As String
    Public Property descripcion As String

    Public Overridable Property Medicamentoes As ICollection(Of Medicamento) = New HashSet(Of Medicamento)

End Class
